// ================================================================
// ADIVINA LA CANCIÓN — Banco de canciones para tararear
// No se reproduce música. Solo se muestran títulos e info.
// ================================================================
const CANCIONES_TARAREO = [

    // ---------- DISNEY Y PIXAR ----------
    { titulo: 'Let It Go', pelicula: 'Frozen', artista: 'Idina Menzel', anio: 2013, categoria: 'Disney' },
    { titulo: 'Libre Soy', pelicula: 'Frozen', artista: 'Idina Menzel', anio: 2013, categoria: 'Disney' },
    { titulo: 'Un hombre te espera', pelicula: 'El Rey León', artista: 'Elton John', anio: 1994, categoria: 'Disney' },
    { titulo: 'Hakuna Matata', pelicula: 'El Rey León', artista: 'Timón y Pumba', anio: 1994, categoria: 'Disney' },
    { titulo: 'El ciclo sin fin', pelicula: 'El Rey León', artista: 'Elton John', anio: 1994, categoria: 'Disney' },
    { titulo: 'Un mundo ideal', pelicula: 'Aladdín', artista: 'Aladdín y Jasmine', anio: 1992, categoria: 'Disney' },
    { titulo: 'Noches de Arabia', pelicula: 'Aladdín', artista: 'Peabo Bryson', anio: 1992, categoria: 'Disney' },
    { titulo: 'Bajo el mar', pelicula: 'La Sirenita', artista: 'Sebastián', anio: 1989, categoria: 'Disney' },
    { titulo: 'Bella y bestia son', pelicula: 'La Bella y la Bestia', artista: 'Celine Dion', anio: 1991, categoria: 'Disney' },
    { titulo: 'Colors of the Wind', pelicula: 'Pocahontas', artista: 'Vanessa Williams', anio: 1995, categoria: 'Disney' },
    { titulo: 'Reflection', pelicula: 'Mulan', artista: 'Christina Aguilera', anio: 1998, categoria: 'Disney' },
    { titulo: 'Cómo me gusta la nieve', pelicula: 'Frozen', artista: 'Olaf', anio: 2013, categoria: 'Disney' },
    { titulo: 'No se habla de Bruno', pelicula: 'Encanto', artista: 'Cast de Encanto', anio: 2021, categoria: 'Disney' },
    { titulo: 'Dos oruguitas', pelicula: 'Encanto', artista: 'Sebastián Yatra', anio: 2021, categoria: 'Disney' },
    { titulo: 'Mira hacia el cielo', pelicula: 'Vaiana', artista: 'Lin-Manuel Miranda', anio: 2016, categoria: 'Disney' },
    { titulo: 'Qué hay más allá', pelicula: 'Vaiana', artista: 'Auliʻi Cravalho', anio: 2016, categoria: 'Disney' },
    { titulo: 'Recuérdame', pelicula: 'Coco', artista: 'Miguel', anio: 2017, categoria: 'Disney' },
    { titulo: 'Un poco loco', pelicula: 'Coco', artista: 'Héctor', anio: 2017, categoria: 'Disney' },
    { titulo: 'Cuando me quieras', pelicula: 'Coco', artista: 'Miguel', anio: 2017, categoria: 'Disney' },
    { titulo: 'Yo soy tu amigo fiel', pelicula: 'Toy Story', artista: 'Randy Newman', anio: 1995, categoria: 'Disney' },
    { titulo: 'Hay un amigo en mí', pelicula: 'Toy Story', artista: 'Joan Manuel Serrat', anio: 1995, categoria: 'Disney' },
    { titulo: 'El mundo es mío', pelicula: 'Aladdín', artista: 'Aladdín', anio: 1992, categoria: 'Disney' },
    { titulo: 'Colores en el viento', pelicula: 'Pocahontas', artista: 'Pocahontas', anio: 1995, categoria: 'Disney' },
    { titulo: 'Supercalifragilisticoespialidoso', pelicula: 'Mary Poppins', artista: 'Julie Andrews', anio: 1964, categoria: 'Disney' },
    { titulo: 'Bibbidi-Bobbidi-Boo', pelicula: 'La Cenicienta', artista: 'Hada Madrina', anio: 1950, categoria: 'Disney' },

    // ---------- BSO DE PELÍCULAS ----------
    { titulo: 'My Heart Will Go On', pelicula: 'Titanic', artista: 'Celine Dion', anio: 1997, categoria: 'BSO' },
    { titulo: 'Eye of the Tiger', pelicula: 'Rocky III', artista: 'Survivor', anio: 1982, categoria: 'BSO' },
    { titulo: 'Ghostbusters', pelicula: 'Cazafantasmas', artista: 'Ray Parker Jr.', anio: 1984, categoria: 'BSO' },
    { titulo: 'I Will Always Love You', pelicula: 'El Guardaespaldas', artista: 'Whitney Houston', anio: 1992, categoria: 'BSO' },
    { titulo: 'Everything I Do', pelicula: 'Robin Hood', artista: 'Bryan Adams', anio: 1991, categoria: 'BSO' },
    { titulo: 'Take My Breath Away', pelicula: 'Top Gun', artista: 'Berlin', anio: 1986, categoria: 'BSO' },
    { titulo: 'Stayin\' Alive', pelicula: 'Fiebre del sábado noche', artista: 'Bee Gees', anio: 1977, categoria: 'BSO' },
    { titulo: 'Footloose', pelicula: 'Footloose', artista: 'Kenny Loggins', anio: 1984, categoria: 'BSO' },
    { titulo: 'Time of My Life', pelicula: 'Dirty Dancing', artista: 'Bill Medley', anio: 1987, categoria: 'BSO' },
    { titulo: 'Lose Yourself', pelicula: '8 Mile', artista: 'Eminem', anio: 2002, categoria: 'BSO' },
    { titulo: 'Skyfall', pelicula: 'Skyfall', artista: 'Adele', anio: 2012, categoria: 'BSO' },
    { titulo: 'Shallow', pelicula: 'Ha nacido una estrella', artista: 'Lady Gaga y Bradley Cooper', anio: 2018, categoria: 'BSO' },
    { titulo: 'Happy', pelicula: 'Gru 2', artista: 'Pharrell Williams', anio: 2013, categoria: 'BSO' },
    { titulo: 'Star Wars (Main Theme)', pelicula: 'Star Wars', artista: 'John Williams', anio: 1977, categoria: 'BSO' },
    { titulo: 'Hedwig\'s Theme', pelicula: 'Harry Potter', artista: 'John Williams', anio: 2001, categoria: 'BSO' },

    // ---------- POP / ROCK INTERNACIONAL ----------
    { titulo: 'Bohemian Rhapsody', artista: 'Queen', anio: 1975, categoria: 'Rock' },
    { titulo: 'We Will Rock You', artista: 'Queen', anio: 1977, categoria: 'Rock' },
    { titulo: 'Don\'t Stop Me Now', artista: 'Queen', anio: 1978, categoria: 'Rock' },
    { titulo: 'Imagine', artista: 'John Lennon', anio: 1971, categoria: 'Mítica' },
    { titulo: 'Hey Jude', artista: 'The Beatles', anio: 1968, categoria: 'Mítica' },
    { titulo: 'Yesterday', artista: 'The Beatles', anio: 1965, categoria: 'Mítica' },
    { titulo: 'Let It Be', artista: 'The Beatles', anio: 1970, categoria: 'Mítica' },
    { titulo: 'Billie Jean', artista: 'Michael Jackson', anio: 1982, categoria: 'Pop' },
    { titulo: 'Thriller', artista: 'Michael Jackson', anio: 1982, categoria: 'Pop' },
    { titulo: 'Beat It', artista: 'Michael Jackson', anio: 1982, categoria: 'Pop' },
    { titulo: 'Like a Virgin', artista: 'Madonna', anio: 1984, categoria: 'Pop' },
    { titulo: 'Material Girl', artista: 'Madonna', anio: 1984, categoria: 'Pop' },
    { titulo: 'Dancing Queen', artista: 'ABBA', anio: 1976, categoria: 'Mítica' },
    { titulo: 'Mamma Mia', artista: 'ABBA', anio: 1975, categoria: 'Mítica' },
    { titulo: 'I Want to Break Free', artista: 'Queen', anio: 1984, categoria: 'Rock' },
    { titulo: 'Sweet Child o\' Mine', artista: 'Guns N\' Roses', anio: 1987, categoria: 'Rock' },
    { titulo: 'Smells Like Teen Spirit', artista: 'Nirvana', anio: 1991, categoria: 'Rock' },
    { titulo: 'Yellow', artista: 'Coldplay', anio: 2000, categoria: 'Pop' },
    { titulo: 'Viva la Vida', artista: 'Coldplay', anio: 2008, categoria: 'Pop' },
    { titulo: 'Rolling in the Deep', artista: 'Adele', anio: 2010, categoria: 'Pop' },
    { titulo: 'Hello', artista: 'Adele', anio: 2015, categoria: 'Pop' },
    { titulo: 'Shape of You', artista: 'Ed Sheeran', anio: 2017, categoria: 'Pop' },
    { titulo: 'Perfect', artista: 'Ed Sheeran', anio: 2017, categoria: 'Pop' },
    { titulo: 'Blinding Lights', artista: 'The Weeknd', anio: 2019, categoria: 'Pop' },
    { titulo: 'Bad Romance', artista: 'Lady Gaga', anio: 2009, categoria: 'Pop' },
    { titulo: 'Poker Face', artista: 'Lady Gaga', anio: 2008, categoria: 'Pop' },
    { titulo: 'Waka Waka', artista: 'Shakira', anio: 2010, categoria: 'Pop' },
    { titulo: 'Umbrella', artista: 'Rihanna', anio: 2007, categoria: 'Pop' },
    { titulo: 'Diamonds', artista: 'Rihanna', anio: 2012, categoria: 'Pop' },
    { titulo: 'Baby One More Time', artista: 'Britney Spears', anio: 1998, categoria: 'Pop' },
    { titulo: 'Toxic', artista: 'Britney Spears', anio: 2004, categoria: 'Pop' },
    { titulo: 'I Will Survive', artista: 'Gloria Gaynor', anio: 1978, categoria: 'Mítica' },
    { titulo: 'Y.M.C.A.', artista: 'Village People', anio: 1978, categoria: 'Mítica' },
    { titulo: 'Every Breath You Take', artista: 'The Police', anio: 1983, categoria: 'Mítica' },
    { titulo: 'Wonderwall', artista: 'Oasis', anio: 1995, categoria: 'Rock' },
    { titulo: 'Nothing Else Matters', artista: 'Metallica', anio: 1991, categoria: 'Rock' },
    { titulo: 'Sweet Dreams', artista: 'Eurythmics', anio: 1983, categoria: 'Mítica' },
    { titulo: 'Losing My Religion', artista: 'R.E.M.', anio: 1991, categoria: 'Rock' },
    { titulo: 'Zombie', artista: 'The Cranberries', anio: 1994, categoria: 'Rock' },

    // ---------- POP / ROCK ESPAÑOL ----------
    { titulo: 'La Macarena', artista: 'Los del Río', anio: 1993, categoria: 'Español' },
    { titulo: 'Yo quiero bailar', artista: 'Sonia y Selena', anio: 1999, categoria: 'Español' },
    { titulo: 'Ave María', artista: 'David Bisbal', anio: 2002, categoria: 'Español' },
    { titulo: 'Bulería', artista: 'David Bisbal', anio: 2004, categoria: 'Español' },
    { titulo: 'La Camisa Negra', artista: 'Juanes', anio: 2004, categoria: 'Español' },
    { titulo: 'Color Esperanza', artista: 'Diego Torres', anio: 2001, categoria: 'Español' },
    { titulo: 'Corazón Espinado', artista: 'Maná', anio: 1999, categoria: 'Español' },
    { titulo: 'Rayando el sol', artista: 'Maná', anio: 1992, categoria: 'Español' },
    { titulo: 'La Bamba', artista: 'Los Lobos', anio: 1987, categoria: 'Español' },
    { titulo: 'Macarena (versión original)', artista: 'Los del Río', anio: 1993, categoria: 'Español' },
    { titulo: 'El himno de la alegría', artista: 'Miguel Ríos', anio: 1969, categoria: 'Español' },
    { titulo: 'Bienvenidos', artista: 'Miguel Ríos', anio: 1982, categoria: 'Español' },
    { titulo: 'Resistiré', artista: 'Dúo Dinámico', anio: 1988, categoria: 'Español' },
    { titulo: 'Un velero llamado libertad', artista: 'José Luis Perales', anio: 1980, categoria: 'Español' },
    { titulo: 'Y cómo es él', artista: 'José Luis Perales', anio: 1982, categoria: 'Español' },
    { titulo: 'Te quiero', artista: 'José Luis Perales', anio: 1979, categoria: 'Español' },
    { titulo: 'Soy rebelde', artista: 'Jeanette', anio: 1971, categoria: 'Español' },
    { titulo: 'Porque te vas', artista: 'Jeanette', anio: 1974, categoria: 'Español' },
    { titulo: 'Hijo de la luna', artista: 'Mecano', anio: 1986, categoria: 'Español' },
    { titulo: 'La fuerza del destino', artista: 'Mecano', anio: 1988, categoria: 'Español' },
    { titulo: 'Mujer contra mujer', artista: 'Mecano', anio: 1988, categoria: 'Español' },
    { titulo: 'Barco a Venus', artista: 'Mecano', anio: 1983, categoria: 'Español' },
    { titulo: 'Devuélveme a mi chica', artista: 'Hombres G', anio: 1985, categoria: 'Español' },
    { titulo: 'Venezia', artista: 'Hombres G', anio: 1986, categoria: 'Español' },
    { titulo: 'Marta tiene un marcapasos', artista: 'Hombres G', anio: 1985, categoria: 'Español' },
    { titulo: 'El sitio de mi recreo', artista: 'Antonio Vega', anio: 1992, categoria: 'Español' },
    { titulo: 'La chispa adecuada', artista: 'Héroes del Silencio', anio: 1995, categoria: 'Español' },
    { titulo: 'Entre dos tierras', artista: 'Héroes del Silencio', anio: 1990, categoria: 'Español' },
    { titulo: 'Maldito duende', artista: 'Héroes del Silencio', anio: 1990, categoria: 'Español' },
    { titulo: 'Corazón partío', artista: 'Alejandro Sanz', anio: 1997, categoria: 'Español' },
    { titulo: 'Amiga mía', artista: 'Alejandro Sanz', anio: 1997, categoria: 'Español' },
    { titulo: 'Y si fuera ella', artista: 'Alejandro Sanz', anio: 1997, categoria: 'Español' },
    { titulo: 'Bailamos', artista: 'Enrique Iglesias', anio: 1999, categoria: 'Español' },
    { titulo: 'Hero', artista: 'Enrique Iglesias', anio: 2001, categoria: 'Español' },
    { titulo: 'Experiencia religiosa', artista: 'Enrique Iglesias', anio: 1995, categoria: 'Español' },
    { titulo: 'La Tortura', artista: 'Shakira y Alejandro Sanz', anio: 2005, categoria: 'Español' },
    { titulo: 'Antología', artista: 'Shakira', anio: 1995, categoria: 'Español' },
    { titulo: 'Ciega, sordomuda', artista: 'Shakira', anio: 1998, categoria: 'Español' },
    { titulo: 'Salir', artista: 'Vetusta Morla', anio: 2008, categoria: 'Español' },
    { titulo: 'Copenhague', artista: 'Vetusta Morla', anio: 2011, categoria: 'Español' },
    { titulo: 'Siete días juntos', artista: 'Vetusta Morla', anio: 2008, categoria: 'Español' },

    // ---------- MÍTICAS ----------
    { titulo: 'My Way', artista: 'Frank Sinatra', anio: 1969, categoria: 'Mítica' },
    { titulo: 'New York, New York', artista: 'Frank Sinatra', anio: 1980, categoria: 'Mítica' },
    { titulo: 'What a Wonderful World', artista: 'Louis Armstrong', anio: 1967, categoria: 'Mítica' },
    { titulo: 'Somewhere Over the Rainbow', artista: 'Judy Garland', anio: 1939, categoria: 'Mítica' },
    { titulo: 'Singing in the Rain', artista: 'Gene Kelly', anio: 1952, categoria: 'Mítica' },
    { titulo: 'Blue Suede Shoes', artista: 'Elvis Presley', anio: 1956, categoria: 'Mítica' },
    { titulo: 'Jailhouse Rock', artista: 'Elvis Presley', anio: 1957, categoria: 'Mítica' },
    { titulo: 'Suspicious Minds', artista: 'Elvis Presley', anio: 1969, categoria: 'Mítica' },
    { titulo: 'No Woman No Cry', artista: 'Bob Marley', anio: 1974, categoria: 'Mítica' },
    { titulo: 'Three Little Birds', artista: 'Bob Marley', anio: 1977, categoria: 'Mítica' },
    { titulo: 'Is This Love', artista: 'Bob Marley', anio: 1978, categoria: 'Mítica' },
    { titulo: 'Hotel California', artista: 'Eagles', anio: 1976, categoria: 'Mítica' },
    { titulo: 'Stairway to Heaven', artista: 'Led Zeppelin', anio: 1971, categoria: 'Mítica' },
    { titulo: 'Sweet Home Alabama', artista: 'Lynyrd Skynyrd', anio: 1974, categoria: 'Mítica' },
    { titulo: 'Like a Rolling Stone', artista: 'Bob Dylan', anio: 1965, categoria: 'Mítica' },
    { titulo: 'Purple Rain', artista: 'Prince', anio: 1984, categoria: 'Mítica' },
    { titulo: 'Kiss', artista: 'Prince', anio: 1986, categoria: 'Mítica' },
    { titulo: 'Nothing Compares 2 U', artista: 'Sinéad O\'Connor', anio: 1990, categoria: 'Mítica' },
    { titulo: 'Hallelujah', artista: 'Leonard Cohen', anio: 1984, categoria: 'Mítica' },
    { titulo: 'Space Oddity', artista: 'David Bowie', anio: 1969, categoria: 'Mítica' },

    // ---------- CLÁSICA ----------
    { titulo: 'Para Elisa', artista: 'Beethoven', anio: 1810, categoria: 'Clásica' },
    { titulo: 'Quinta Sinfonía', artista: 'Beethoven', anio: 1808, categoria: 'Clásica' },
    { titulo: 'Novena Sinfonía (Himno a la Alegría)', artista: 'Beethoven', anio: 1824, categoria: 'Clásica' },
    { titulo: 'Pequeña serenata nocturna', artista: 'Mozart', anio: 1787, categoria: 'Clásica' },
    { titulo: 'Marcha Turca', artista: 'Mozart', anio: 1783, categoria: 'Clásica' },
    { titulo: 'Las cuatro estaciones - Primavera', artista: 'Vivaldi', anio: 1725, categoria: 'Clásica' },
    { titulo: 'Canon en Re Mayor', artista: 'Pachelbel', anio: 1680, categoria: 'Clásica' },
    { titulo: 'Claro de Luna', artista: 'Debussy', anio: 1905, categoria: 'Clásica' },
    { titulo: 'El lago de los cisnes', artista: 'Tchaikovsky', anio: 1876, categoria: 'Clásica' },
    { titulo: 'Danza del Hada de Azúcar', artista: 'Tchaikovsky', anio: 1892, categoria: 'Clásica' },

    // ---------- VILLANCICOS Y TRADICIONALES ----------
    { titulo: 'Noche de Paz', artista: 'Tradicional', anio: 1818, categoria: 'Villancico' },
    { titulo: 'Los peces en el río', artista: 'Tradicional', anio: 0, categoria: 'Villancico' },
    { titulo: 'Campana sobre campana', artista: 'Tradicional', anio: 0, categoria: 'Villancico' },
    { titulo: 'Ya vienen los Reyes Magos', artista: 'Tradicional', anio: 0, categoria: 'Villancico' },
    { titulo: 'Blanca Navidad', artista: 'Bing Crosby', anio: 1942, categoria: 'Villancico' },
    { titulo: 'Jingle Bells', artista: 'Tradicional', anio: 1857, categoria: 'Villancico' },
    { titulo: 'Rodolfo el Reno', artista: 'Tradicional', anio: 1949, categoria: 'Villancico' },
    { titulo: 'Feliz Navidad', artista: 'José Feliciano', anio: 1970, categoria: 'Villancico' },
    { titulo: 'All I Want for Christmas Is You', artista: 'Mariah Carey', anio: 1994, categoria: 'Villancico' },
    { titulo: 'Last Christmas', artista: 'Wham!', anio: 1984, categoria: 'Villancico' },

    // ---------- LAS MÁS ESCUCHADAS / ACTUALES ----------
    { titulo: 'Despacito', artista: 'Luis Fonsi', anio: 2017, categoria: 'Actual' },
    { titulo: 'Tusa', artista: 'Karol G y Nicki Minaj', anio: 2019, categoria: 'Actual' },
    { titulo: 'Todo de Ti', artista: 'Rauw Alejandro', anio: 2021, categoria: 'Actual' },
    { titulo: 'Tití Me Preguntó', artista: 'Bad Bunny', anio: 2022, categoria: 'Actual' },
    { titulo: 'Me Porto Bonito', artista: 'Bad Bunny', anio: 2022, categoria: 'Actual' },
    { titulo: 'Como Camarón', artista: 'Estopa', anio: 1999, categoria: 'Español' },
    { titulo: 'Por la boca vive el pez', artista: 'Fito & Fitipaldis', anio: 2006, categoria: 'Español' },
    { titulo: 'Soldadito marinero', artista: 'Fito & Fitipaldis', anio: 2001, categoria: 'Español' },
    { titulo: 'La flaca', artista: 'Jarabe de Palo', anio: 1996, categoria: 'Español' },
    { titulo: 'Depende', artista: 'Jarabe de Palo', anio: 1998, categoria: 'Español' },
    { titulo: 'Un beso y una flor', artista: 'Nino Bravo', anio: 1972, categoria: 'Español' },
    { titulo: 'Libre', artista: 'Nino Bravo', anio: 1972, categoria: 'Español' },
    { titulo: 'Mi gran noche', artista: 'Raphael', anio: 1968, categoria: 'Español' },
    { titulo: 'Yo soy aquel', artista: 'Raphael', anio: 1966, categoria: 'Español' },
    { titulo: 'Como una ola', artista: 'Rocío Jurado', anio: 1981, categoria: 'Español' },
    { titulo: 'Se nos rompió el amor', artista: 'Rocío Jurado', anio: 1984, categoria: 'Español' },
    { titulo: 'A tu lado', artista: 'Los Secretos', anio: 1980, categoria: 'Español' },
    { titulo: 'Déjame', artista: 'Los Secretos', anio: 1981, categoria: 'Español' },
    { titulo: 'Chiquilla', artista: 'Seguridad Social', anio: 1990, categoria: 'Español' },
    { titulo: 'La puerta de Alcalá', artista: 'Ana Belén y Víctor Manuel', anio: 1986, categoria: 'Español' },
    { titulo: 'Solo pienso en ti', artista: 'Víctor Manuel', anio: 1979, categoria: 'Español' },
    { titulo: 'Asturias', artista: 'Víctor Manuel', anio: 1970, categoria: 'Español' },
    { titulo: 'Eres tú', artista: 'Mocedades', anio: 1973, categoria: 'Español' },
    { titulo: 'Amante bandido', artista: 'Miguel Bosé', anio: 1984, categoria: 'Español' },
    { titulo: 'Nena', artista: 'Miguel Bosé', anio: 1980, categoria: 'Español' },

    // ---------- CANCIONES INFANTILES ----------
    { titulo: 'Cumpleaños Feliz', artista: 'Tradicional', anio: 1893, categoria: 'Infantil' },
    { titulo: 'Estrellita, ¿dónde estás?', artista: 'Tradicional', anio: 1806, categoria: 'Infantil' },
    { titulo: 'Los pollitos dicen', artista: 'Tradicional', anio: 0, categoria: 'Infantil' },
    { titulo: 'El patio de mi casa', artista: 'Tradicional', anio: 0, categoria: 'Infantil' },
    { titulo: 'Al corro de la patata', artista: 'Tradicional', anio: 0, categoria: 'Infantil' },
    { titulo: 'La vaca lechera', artista: 'Tradicional', anio: 0, categoria: 'Infantil' },
    { titulo: 'Vamos a contar mentiras', artista: 'Tradicional', anio: 0, categoria: 'Infantil' },
    { titulo: 'Soy una taza', artista: 'CantaJuego', anio: 2005, categoria: 'Infantil' },
    { titulo: 'El baile del pingüino', artista: 'CantaJuego', anio: 2005, categoria: 'Infantil' },
    { titulo: 'El Rock de la Cárcel', artista: 'Parchís', anio: 1981, categoria: 'Infantil' },

    // ---------- HIMNOS Y MARCHAS ----------
    { titulo: 'Himno Nacional de España', artista: 'Tradicional', anio: 1770, categoria: 'Himno' },
    { titulo: 'La Marsellesa', artista: 'Tradicional', anio: 1792, categoria: 'Himno' },
    { titulo: 'God Save the Queen', artista: 'Tradicional', anio: 1745, categoria: 'Himno' },
    { titulo: 'Star-Spangled Banner', artista: 'Tradicional', anio: 1814, categoria: 'Himno' },

    // ---------- OTROS CLÁSICOS MODERNOS ----------
    { titulo: 'Wonderful Tonight', artista: 'Eric Clapton', anio: 1977, categoria: 'Mítica' },
    { titulo: 'Tears in Heaven', artista: 'Eric Clapton', anio: 1992, categoria: 'Mítica' },
    { titulo: 'Angels', artista: 'Robbie Williams', anio: 1997, categoria: 'Pop' },
    { titulo: 'Feel', artista: 'Robbie Williams', anio: 2002, categoria: 'Pop' },
    { titulo: 'Creep', artista: 'Radiohead', anio: 1992, categoria: 'Rock' },
    { titulo: 'Karma Police', artista: 'Radiohead', anio: 1997, categoria: 'Rock' },
    { titulo: 'Fix You', artista: 'Coldplay', anio: 2005, categoria: 'Pop' },
    { titulo: 'A Sky Full of Stars', artista: 'Coldplay', anio: 2014, categoria: 'Pop' },
    { titulo: 'Chandelier', artista: 'Sia', anio: 2014, categoria: 'Pop' },
    { titulo: 'Someone Like You', artista: 'Adele', anio: 2011, categoria: 'Pop' },
    { titulo: 'Shake It Off', artista: 'Taylor Swift', anio: 2014, categoria: 'Pop' },
    { titulo: 'Love Story', artista: 'Taylor Swift', anio: 2008, categoria: 'Pop' },
    { titulo: 'Uptown Funk', artista: 'Mark Ronson y Bruno Mars', anio: 2014, categoria: 'Pop' },
    { titulo: 'Just the Way You Are', artista: 'Bruno Mars', anio: 2010, categoria: 'Pop' },
    { titulo: 'Havana', artista: 'Camila Cabello', anio: 2017, categoria: 'Pop' }
];

// ----------------------------------------------------------------
// HELPERS
// ----------------------------------------------------------------
function barajarCanciones(arr) {
    const copia = [...arr];
    for (let i = copia.length - 1; i > 0; i--) {
        const j = Math.floor(Math.random() * (i + 1));
        [copia[i], copia[j]] = [copia[j], copia[i]];
    }
    return copia;
}

function obtenerCancionAleatoria() {
    return CANCIONES_TARAREO[Math.floor(Math.random() * CANCIONES_TARAREO.length)];
}

function formatearAnio(anio) {
    if (!anio || anio === 0) return 'Tradicional';
    if (anio < 0) return Math.abs(anio) + ' a.C.';
    return anio;
}