// ================================================================
// ¿QUIÉN SOY? — Banco de personajes
// Los que tienen { nombre, universo, anio, frase } muestran tarjeta bonita.
// Los que son solo texto (string) muestran tarjeta simple.
// ================================================================
const BANCO_PERSONAJES_QUIENSOY = [

    // ---------- MARVEL ----------
    { nombre: 'Spider-Man', universo: 'Marvel', anio: 1962, frase: 'Es el alter ego del joven Peter Parker.' },
    { nombre: 'Iron Man', universo: 'Marvel', anio: 1963, frase: 'Su identidad secreta es el millonario Tony Stark.' },
    { nombre: 'Hulk', universo: 'Marvel', anio: 1962, frase: 'Es el alter ego del científico Bruce Banner.' },
    { nombre: 'Thor', universo: 'Marvel', anio: 1962, frase: 'Es el dios del trueno, hijo de Odín.' },
    { nombre: 'Capitán América', universo: 'Marvel', anio: 1941, frase: 'Su escudo es tan famoso como su traje.' },
    { nombre: 'Viuda Negra', universo: 'Marvel', anio: 1964, frase: 'Su nombre real es Natasha Romanoff.' },
    { nombre: 'Black Panther', universo: 'Marvel', anio: 1966, frase: 'Es el rey de Wakanda.' },
    { nombre: 'Doctor Strange', universo: 'Marvel', anio: 1963, frase: 'Es el Hechicero Supremo de la Tierra.' },
    { nombre: 'Loki', universo: 'Marvel', anio: 1962, frase: 'Es el hermano adoptivo de Thor.' },
    { nombre: 'Thanos', universo: 'Marvel', anio: 1973, frase: 'Quiere eliminar a la mitad del universo.' },
    { nombre: 'Magneto', universo: 'Marvel', anio: 1963, frase: 'Es el villano que controla el metal.' },
    { nombre: 'Deadpool', universo: 'Marvel', anio: 1991, frase: 'Es el mercenario bocazas que rompe la cuarta pared.' },
    { nombre: 'Wolverine', universo: 'Marvel', anio: 1974, frase: 'Tiene garras de adamantium y curación acelerada.' },
    { nombre: 'Groot', universo: 'Marvel', anio: 1960, frase: 'Solo dice una frase: "I am Groot".' },
    { nombre: 'Star-Lord', universo: 'Marvel', anio: 1976, frase: 'Es el líder de los Guardianes de la Galaxia.' },

    // ---------- DC ----------
    { nombre: 'Batman', universo: 'DC Cómics', anio: 1939, frase: 'Su identidad secreta es el millonario Bruce Wayne.' },
    { nombre: 'Superman', universo: 'DC Cómics', anio: 1938, frase: 'Nació en el planeta Krypton.' },
    { nombre: 'Wonder Woman', universo: 'DC Cómics', anio: 1941, frase: 'Es la princesa amazona Diana de Themyscira.' },
    { nombre: 'Flash', universo: 'DC Cómics', anio: 1940, frase: 'Es el hombre más rápido del mundo.' },
    { nombre: 'Aquaman', universo: 'DC Cómics', anio: 1941, frase: 'Es el rey de la Atlántida.' },
    { nombre: 'El Joker', universo: 'DC Cómics', anio: 1940, frase: 'Es el archienemigo de Batman.' },
    { nombre: 'El Pingüino', universo: 'DC Cómics', anio: 1941, frase: 'Es un villano bajito con paraguas y puro.' },
    { nombre: 'Harley Quinn', universo: 'DC Cómics', anio: 1992, frase: 'Es psiquiatra y novia del Joker.' },
    { nombre: 'Robin', universo: 'DC Cómics', anio: 1940, frase: 'Es el compañero adolescente de Batman.' },
    { nombre: 'Catwoman', universo: 'DC Cómics', anio: 1940, frase: 'Es una ladrona con traje de gato.' },
    { nombre: 'Green Lantern', universo: 'DC Cómics', anio: 1940, frase: 'Su anillo verde crea lo que imagina.' },
    { nombre: 'Cyborg', universo: 'DC Cómics', anio: 1980, frase: 'Es mitad humano, mitad máquina.' },

    // ---------- DISNEY Y PIXAR ----------
    { nombre: 'Mickey Mouse', universo: 'Disney', anio: 1928, frase: 'Es el ratón más famoso del mundo.' },
    { nombre: 'Pato Donald', universo: 'Disney', anio: 1934, frase: 'Es el pato gruñón con camisa de marinero.' },
    { nombre: 'Goofy', universo: 'Disney', anio: 1932, frase: 'Es el perro alto y despistado, amigo de Mickey.' },
    { nombre: 'Blancanieves', universo: 'Disney', anio: 1937, frase: 'Vive con siete enanitos en el bosque.' },
    { nombre: 'La Cenicienta', universo: 'Disney', anio: 1950, frase: 'Pierde un zapato de cristal en el baile.' },
    { nombre: 'Rapunzel', universo: 'Disney', anio: 2010, frase: 'Tiene el pelo larguísimo y vive en una torre.' },
    { nombre: 'Aurora', universo: 'Disney', anio: 1959, frase: 'Es La Bella Durmiente, duerme 100 años.' },
    { nombre: 'Ariel', universo: 'Disney', anio: 1989, frase: 'Es la sirenita que quiere ser humana.' },
    { nombre: 'Elsa de Frozen', universo: 'Disney', anio: 2013, frase: 'Tiene poderes de hielo y canta "Let It Go".' },
    { nombre: 'Anna de Frozen', universo: 'Disney', anio: 2013, frase: 'Es la hermana pequeña de Elsa.' },
    { nombre: 'Olaf', universo: 'Disney', anio: 2013, frase: 'Es el muñeco de nieve que sueña con el verano.' },
    { nombre: 'Buzz Lightyear', universo: 'Pixar', anio: 1995, frase: 'Es el guardián espacial que cree ser real.' },
    { nombre: 'Woody', universo: 'Pixar', anio: 1995, frase: 'Es el vaquero de juguete líder de Andy.' },
    { nombre: 'Nemo', universo: 'Pixar', anio: 2003, frase: 'Es el pez payaso que se pierde en el océano.' },
    { nombre: 'Dory', universo: 'Pixar', anio: 2003, frase: 'Es el pez azul con problemas de memoria.' },
    { nombre: 'Simba', universo: 'Disney', anio: 1994, frase: 'Es el cachorro de león que será rey.' },
    { nombre: 'Timón', universo: 'Disney', anio: 1994, frase: 'Es el suricato amigo de Simba.' },
    { nombre: 'Pumba', universo: 'Disney', anio: 1994, frase: 'Es el jabalí amigo de Simba.' },
    { nombre: 'Aladino', universo: 'Disney', anio: 1992, frase: 'Encuentra una lámpara mágica con un genio.' },
    { nombre: 'Jasmine', universo: 'Disney', anio: 1992, frase: 'Es la princesa de Agrabah con un tigre.' },
    { nombre: 'El Genio', universo: 'Disney', anio: 1992, frase: 'Es el genio azul que concede tres deseos.' },
    { nombre: 'Pinocho', universo: 'Disney', anio: 1940, frase: 'Es el muñeco de madera que quiere ser niño real.' },
    { nombre: 'Peter Pan', universo: 'Disney', anio: 1953, frase: 'Es el niño que no quiere crecer y vuela.' },
    { nombre: 'Campanilla', universo: 'Disney', anio: 1953, frase: 'Es el hada pequeña con polvo mágico.' },
    { nombre: 'Dumbo', universo: 'Disney', anio: 1941, frase: 'Es el elefante que vuela con sus orejas.' },
    { nombre: 'Mulan', universo: 'Disney', anio: 1998, frase: 'Se disfraza de hombre para ir a la guerra.' },
    { nombre: 'Vaiana', universo: 'Disney', anio: 2016, frase: 'Es la navegante que cruza el océano.' },
    { nombre: 'Mirabel', universo: 'Disney', anio: 2021, frase: 'Es la única de su familia sin poderes mágicos.' },
    { nombre: 'Winnie the Pooh', universo: 'Disney', anio: 1926, frase: 'Es el oso amarillo amante de la miel.' },
    { nombre: 'Stitch', universo: 'Disney', anio: 2002, frase: 'Es el alien azul adoptado por Lilo.' },
    { nombre: 'WALL-E', universo: 'Pixar', anio: 2008, frase: 'Es el robot basurero que se enamora.' },
    { nombre: 'Remy', universo: 'Pixar', anio: 2007, frase: 'Es la rata que cocina en París.' },
    { nombre: 'Mr. Increíble', universo: 'Pixar', anio: 2004, frase: 'Es el superhéroe fuerte retirado.' },
    { nombre: 'Elastigirl', universo: 'Pixar', anio: 2004, frase: 'Es la superheroína elástica.' },
    { nombre: 'Miguel', universo: 'Pixar', anio: 2017, frase: 'Es el niño que quiere ser músico en Coco.' },

    // ---------- STAR WARS ----------
    { nombre: 'Darth Vader', universo: 'Star Wars', anio: 1977, frase: 'Es el padre de Luke Skywalker.' },
    { nombre: 'Luke Skywalker', universo: 'Star Wars', anio: 1977, frase: 'Es el joven jedi que salva la galaxia.' },
    { nombre: 'Yoda', universo: 'Star Wars', anio: 1980, frase: 'Es el maestro jedi verde y orejudo.' },
    { nombre: 'Chewbacca', universo: 'Star Wars', anio: 1977, frase: 'Es el wookie peludo copiloto de Han Solo.' },
    { nombre: 'Han Solo', universo: 'Star Wars', anio: 1977, frase: 'Es el contrabandista capitán del Halcón Milenario.' },
    { nombre: 'Leia Organa', universo: 'Star Wars', anio: 1977, frase: 'Es la princesa rebelde hermana de Luke.' },
    { nombre: 'Obi-Wan Kenobi', universo: 'Star Wars', anio: 1977, frase: 'Es el maestro jedi que entrena a Luke.' },
    { nombre: 'Kylo Ren', universo: 'Star Wars', anio: 2015, frase: 'Es el villano con sable rojo hijo de Han y Leia.' },
    { nombre: 'R2-D2', universo: 'Star Wars', anio: 1977, frase: 'Es el droide astromecánico azul y blanco.' },
    { nombre: 'C-3PO', universo: 'Star Wars', anio: 1977, frase: 'Es el droide de protocolo dorado.' },

    // ---------- ANIME ----------
    { nombre: 'Goku', universo: 'Dragon Ball', anio: 1984, frase: 'Es el saiyan que protege la Tierra.' },
    { nombre: 'Vegeta', universo: 'Dragon Ball', anio: 1988, frase: 'Es el príncipe saiyan orgulloso.' },
    { nombre: 'Naruto', universo: 'Naruto', anio: 1999, frase: 'Es el ninja con un zorro dentro.' },
    { nombre: 'Sasuke', universo: 'Naruto', anio: 1999, frase: 'Es el rival y mejor amigo de Naruto.' },
    { nombre: 'Luffy', universo: 'One Piece', anio: 1997, frase: 'Es el capitán de los Sombrero de Paja.' },
    { nombre: 'Zoro', universo: 'One Piece', anio: 1997, frase: 'Es el espadachín de tres espadas.' },
    { nombre: 'Sailor Moon', universo: 'Sailor Moon', anio: 1991, frase: 'Es la guerrera con traje de marinera.' },
    { nombre: 'Pikachu', universo: 'Pokémon', anio: 1996, frase: 'Es el ratón eléctrico amarillo.' },
    { nombre: 'Ash Ketchum', universo: 'Pokémon', anio: 1996, frase: 'Es el entrenador que quiere ser maestro Pokémon.' },
    { nombre: 'Doraemon', universo: 'Doraemon', anio: 1969, frase: 'Es el gato cósmico con bolsillo mágico.' },

    // ---------- DIBUJOS ANIMADOS ----------
    { nombre: 'Homer Simpson', universo: 'Los Simpsons', anio: 1987, frase: 'Es el padre calvo aficionado a las donuts.' },
    { nombre: 'Marge Simpson', universo: 'Los Simpsons', anio: 1987, frase: 'Es la madre con pelo azul y cardado.' },
    { nombre: 'Bart Simpson', universo: 'Los Simpsons', anio: 1987, frase: 'Es el niño travieso con pelo de punta.' },
    { nombre: 'Lisa Simpson', universo: 'Los Simpsons', anio: 1987, frase: 'Es la hija inteligente y saxofonista.' },
    { nombre: 'Bob Esponja', universo: 'Bob Esponja', anio: 1999, frase: 'Es la esponja amarilla que vive en una piña.' },
    { nombre: 'Patricio Estrella', universo: 'Bob Esponja', anio: 1999, frase: 'Es la estrella de mar rosa, amiga de Bob.' },
    { nombre: 'Calamardo', universo: 'Bob Esponja', anio: 1999, frase: 'Es el calamar gruñón vecino de Bob.' },
    { nombre: 'Scooby-Doo', universo: 'Scooby-Doo', anio: 1969, frase: 'Es el perro cobarde que resuelve misterios.' },
    { nombre: 'Shaggy', universo: 'Scooby-Doo', anio: 1969, frase: 'Es el dueño flaco y hambriento de Scooby.' },
    { nombre: 'Tom', universo: 'Tom y Jerry', anio: 1940, frase: 'Es el gato que siempre persigue al ratón.' },
    { nombre: 'Jerry', universo: 'Tom y Jerry', anio: 1940, frase: 'Es el ratón escurridizo que se escapa.' },
    { nombre: 'Bugs Bunny', universo: 'Looney Tunes', anio: 1940, frase: 'Es el conejo de la zanahoria.' },
    { nombre: 'Pato Lucas', universo: 'Looney Tunes', anio: 1937, frase: 'Es el pato negro gruñón y envidioso.' },
    { nombre: 'Popeye', universo: 'Popeye', anio: 1929, frase: 'Es el marinero que saca fuerza de las espinacas.' },
    { nombre: 'Mortadelo', universo: 'Mortadelo y Filemón', anio: 1958, frase: 'Es el calvo con disfraces infinitos.' },

    // ---------- CINE Y TELEVISIÓN ----------
    { nombre: 'Indiana Jones', universo: 'Indiana Jones', anio: 1981, frase: 'Es el arqueólogo con látigo y sombrero.' },
    { nombre: 'James Bond', universo: 'James Bond', anio: 1953, frase: 'Es el espía 007 con licencia para matar.' },
    { nombre: 'Rocky Balboa', universo: 'Rocky', anio: 1976, frase: 'Es el boxeador de Filadelfia.' },
    { nombre: 'Terminator', universo: 'Terminator', anio: 1984, frase: 'Es el robot que dice "I\'ll be back".' },
    { nombre: 'Neo', universo: 'Matrix', anio: 1999, frase: 'Es el elegido que esquiva balas.' },
    { nombre: 'Gandalf', universo: 'El Señor de los Anillos', anio: 1937, frase: 'Es el mago con barba larga y bastón.' },
    { nombre: 'Frodo', universo: 'El Señor de los Anillos', anio: 1937, frase: 'Es el hobbit que lleva el Anillo Único.' },
    { nombre: 'Gollum', universo: 'El Señor de los Anillos', anio: 1937, frase: 'Es la criatura obsesionada con "su tesoro".' },
    { nombre: 'Jack Sparrow', universo: 'Piratas del Caribe', anio: 2003, frase: 'Es el pirata capitán de la Perla Negra.' },
    { nombre: 'Harry Potter', universo: 'Harry Potter', anio: 1997, frase: 'Es el niño mago con la cicatriz en la frente.' },
    { nombre: 'Hermione Granger', universo: 'Harry Potter', anio: 1997, frase: 'Es la bruja más lista de Hogwarts.' },
    { nombre: 'Dumbledore', universo: 'Harry Potter', anio: 1997, frase: 'Es el director de Hogwarts con barba blanca.' },
    { nombre: 'Voldemort', universo: 'Harry Potter', anio: 1997, frase: 'Es el mago oscuro al que no se debe nombrar.' },
    { nombre: 'Drácula', universo: 'Drácula', anio: 1897, frase: 'Es el conde vampiro de Transilvania.' },
    { nombre: 'Sherlock Holmes', universo: 'Sherlock Holmes', anio: 1887, frase: 'Es el detective con gorra y lupa.' },

    // ---------- HISTÓRICOS ----------
    { nombre: 'Cleopatra', universo: 'Histórico', anio: -69, frase: 'Fue la última faraona de Egipto.' },
    { nombre: 'Julio César', universo: 'Histórico', anio: -100, frase: 'Fue emperador romano asesinado en el Senado.' },
    { nombre: 'Napoleón Bonaparte', universo: 'Histórico', anio: 1769, frase: 'Fue emperador francés exiliado en Santa Elena.' },
    { nombre: 'Leonardo da Vinci', universo: 'Histórico', anio: 1452, frase: 'Pintó la Mona Lisa y La Última Cena.' },
    { nombre: 'Albert Einstein', universo: 'Histórico', anio: 1879, frase: 'Formuló la teoría de la relatividad.' },
    { nombre: 'Isaac Newton', universo: 'Histórico', anio: 1643, frase: 'Descubrió la ley de la gravedad.' },
    { nombre: 'Marie Curie', universo: 'Histórico', anio: 1867, frase: 'Ganó dos premios Nobel, uno de Física y otro de Química.' },
    { nombre: 'Mozart', universo: 'Histórico', anio: 1756, frase: 'Fue un genio de la música desde niño.' },
    { nombre: 'Beethoven', universo: 'Histórico', anio: 1770, frase: 'Compuso sordo la Novena Sinfonía.' },
    { nombre: 'Van Gogh', universo: 'Histórico', anio: 1853, frase: 'Pintó "La noche estrellada".' },
    { nombre: 'Frida Kahlo', universo: 'Histórico', anio: 1907, frase: 'Pintora mexicana de cejas y flores.' },
    { nombre: 'Picasso', universo: 'Histórico', anio: 1881, frase: 'Fue el padre del cubismo.' },
    { nombre: 'Cristóbal Colón', universo: 'Histórico', anio: 1451, frase: 'Llegó a América en 1492.' },
    { nombre: 'Gandhi', universo: 'Histórico', anio: 1869, frase: 'Lideró la independencia de la India sin violencia.' },
    { nombre: 'Martin Luther King', universo: 'Histórico', anio: 1929, frase: 'Tenía un sueño: igualdad racial.' },

    // ---------- DEPORTISTAS ----------
    { nombre: 'Lionel Messi', universo: 'Deportes', anio: 1987, frase: 'Futbolista argentino con 8 Balones de Oro.' },
    { nombre: 'Cristiano Ronaldo', universo: 'Deportes', anio: 1985, frase: 'Futbolista portugués del "Siuuu".' },
    { nombre: 'Michael Jordan', universo: 'Deportes', anio: 1963, frase: 'Es el mejor jugador de baloncesto de la historia.' },
    { nombre: 'Rafa Nadal', universo: 'Deportes', anio: 1986, frase: 'Tenista español con 22 Grand Slams.' },
    { nombre: 'Roger Federer', universo: 'Deportes', anio: 1981, frase: 'Tenista suizo elegante y sonriente.' },
    { nombre: 'Serena Williams', universo: 'Deportes', anio: 1981, frase: 'Tenista estadounidense con 23 Grand Slams.' },
    { nombre: 'Usain Bolt', universo: 'Deportes', anio: 1986, frase: 'Es el hombre más rápido del mundo.' },
    { nombre: 'Michael Phelps', universo: 'Deportes', anio: 1985, frase: 'Es el nadador con más medallas olímpicas.' },
    { nombre: 'Fernando Alonso', universo: 'Deportes', anio: 1981, frase: 'Piloto español de Fórmula 1 bicampeón.' },
    { nombre: 'Diego Maradona', universo: 'Deportes', anio: 1960, frase: 'Futbolista argentino de la "Mano de Dios".' },

    // ---------- MÚSICA ----------
    { nombre: 'Michael Jackson', universo: 'Música', anio: 1958, frase: 'Es el rey del pop, famoso por el moonwalk.' },
    { nombre: 'Freddie Mercury', universo: 'Música', anio: 1946, frase: 'Fue el cantante de Queen.' },
    { nombre: 'Elvis Presley', universo: 'Música', anio: 1935, frase: 'Es el rey del rock and roll.' },
    { nombre: 'John Lennon', universo: 'Música', anio: 1940, frase: 'Fue miembro de The Beatles.' },
    { nombre: 'Bob Marley', universo: 'Música', anio: 1945, frase: 'Es el rey del reggae.' },
    { nombre: 'Madonna', universo: 'Música', anio: 1958, frase: 'Es la reina del pop.' },
    { nombre: 'David Bowie', universo: 'Música', anio: 1947, frase: 'Tenía un alter ego llamado Ziggy Stardust.' },
    { nombre: 'Rosalía', universo: 'Música', anio: 1992, frase: 'Cantante española famosa por "Despechá".' },
    { nombre: 'Shakira', universo: 'Música', anio: 1977, frase: 'Sus caderas no mienten.' },
    { nombre: 'Ricky Martin', universo: 'Música', anio: 1971, frase: 'Cantante puertorriqueño de "Livin\' la Vida Loca".' },

    // ---------- STREAMERS ----------
    { nombre: 'Ibai Llanos', universo: 'Streamer', anio: 1995, frase: 'Organiza La Velada del Año.' },
    { nombre: 'El Rubius', universo: 'Streamer', anio: 1990, frase: 'Youtuber español con más suscriptores.' },
    { nombre: 'AuronPlay', universo: 'Streamer', anio: 1988, frase: 'Streamer catalán de las bromas telefónicas.' },
    { nombre: 'TheGrefg', universo: 'Streamer', anio: 1997, frase: 'Streamer murciano que reveló su skin de Fortnite.' },
    { nombre: 'Vegetta777', universo: 'Streamer', anio: 1989, frase: 'Youtuber español de Minecraft.' },

    // ---------- LITERATURA Y CUENTOS ----------
    { nombre: 'Don Quijote', universo: 'Literatura', anio: 1605, frase: 'Luchó contra molinos creyendo que eran gigantes.' },
    { nombre: 'Caperucita Roja', universo: 'Cuento', anio: 1697, frase: 'Lleva una cesta a su abuela.' },
    { nombre: 'El Lobo Feroz', universo: 'Cuento', anio: 1697, frase: 'Sopla casas y se disfraza de abuela.' },
    { nombre: 'Robin Hood', universo: 'Literatura', anio: 1400, frase: 'Robaba a los ricos para dar a los pobres.' },
    { nombre: 'Tarzán', universo: 'Literatura', anio: 1912, frase: 'Fue criado por simios en la selva.' },
    { nombre: 'Mowgli', universo: 'Literatura', anio: 1894, frase: 'Es el niño criado por lobos en la selva.' },
    { nombre: 'El Principito', universo: 'Literatura', anio: 1943, frase: 'Vive en un asteroide con una rosa.' },
    { nombre: 'Pippi Calzaslargas', universo: 'Literatura', anio: 1945, frase: 'Es la niña más fuerte del mundo.' },
    { nombre: 'Alicia', universo: 'Literatura', anio: 1865, frase: 'Cae por una madriguera al País de las Maravillas.' },
    { nombre: 'Hamlet', universo: 'Literatura', anio: 1601, frase: 'Es el príncipe danés que dice "ser o no ser".' },

    // ---------- ROLES GENÉRICOS (tarjeta simple) ----------
    'Un pirata',
    'Un astronauta',
    'Un bombero',
    'Un detective privado',
    'Un vaquero del oeste',
    'Un ninja',
    'Un samurái',
    'Un zombi',
    'Un fantasma',
    'Un vampiro',
    'Una bruja de cuento',
    'Un mago',
    'Un superhéroe inventado',
    'Un extraterrestre',
    'Un dinosaurio famoso',
    'Un futbolista muy conocido',
    'Un cantante famoso',
    'Un rey medieval',
    'Tu profesor favorito del colegio',
    'Un influencer inventado',
    'Un youtuber famoso',
    'Un chef con estrella Michelin',
    'Un científico loco',
    'Un superhéroe con capa verde',
    'Un extraterrestre verde'
];